# Generated by Django 6.0.3 on 2026-03-15 22:31

from django.db import migrations

def create_default_categories(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Category = apps.get_model('todo', 'Category')
    
    DEFAULT_CATEGORIES = [
        {"name": "random thoughts", "color": "#EF9C66"},
        {"name": "personal", "color": "#78ABA8"},
        {"name": "school", "color": "#FCDC94"},
        {"name": "drama", "color": "#C8CFA0"},
    ]
    
    for user in User.objects.all():
        for cat_data in DEFAULT_CATEGORIES:
            Category.objects.get_or_create(
                owner=user,
                name=cat_data["name"],
                defaults={"color": cat_data["color"]}
            )

def reverse_default_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category_todo_category'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
